version: "3.8"
services:

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=forum
      - POSTGRES_USER=forum_admin
      - POSTGRES_PASSWORD=forumadmin
      - POSTGRES_ENGINE=django.db.backends.postgresql
      - POSTGRES_PORT=5432
      

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-forum
    ports:
      - "8000:8000"
    container_name: forum_app

    environment:
      - POSTGRES_DB=forum
      - POSTGRES_USER=forum_admin
      - POSTGRES_PASSWORD=forumadmin
      - POSTGRES_ENGINE=django.db.backends.postgresql
      - POSTGRES_PORT=5432
      
  
    depends_on:
      - db


  celery:
    restart: always
    build: 
      context: .

    command: celery -A forum worker -l INFO
    
    volumes:
      - .:/django-forum
    container_name: celery
    depends_on:
      - db
      - redis
      - app